name: Sync and Package Helm Chart

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout main
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Needed to push later

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.18.4

      - name: Package Helm Chart
        run: |
          helm package .
          helm repo index . --url https://anlowee.github.io/yscope-k8s

      - name: Commit index.yaml to main branch
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add index.yaml
          git commit -m "Update index.yaml after packaging Helm chart" || echo "No changes"
          git push origin main

      - name: Checkout gh-pages
        uses: actions/checkout@v4
        with:
          ref: gh-pages
          path: gh-pages
          fetch-depth: 0

      - name: Copy chart package and index.yaml to gh-pages
        run: |
          cp *.tgz gh-pages/
          cp index.yaml gh-pages/

      - name: Commit and push to gh-pages
        run: |
          cd gh-pages
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Update index.yaml and Helm chart package" || echo "No changes"
          git push origin gh-pages

